apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: microdemo
spec:
  type: LoadBalancer
  selector:
    app: my-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  namespace: microdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: my-api-app:1.0
        ports:
        - containerPort: 3000
